#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
    /config/{crontabs,www/freshrss}

# create symlinks
ln -s /app/www/p /app/www/public
symlinks=( \
/app/www/public/data \
/app/www/public/extensions )

for i in "${symlinks[@]}"
do
[[ -e "$i" && ! -L "$i" ]] && mv "$i" "${i}.bak"
[[ ! -L "$i" ]] && ln -s "/config/www/freshrss/$(basename "$i")" "$i"
[[ ! -d "/config/www/freshrss/$(basename "$i")" ]] && \
    cp -R "${i}.bak" "/config/www/freshrss/$(basename "$i")"
done

# backwards compatibility
if grep -q 'root /config/www/freshrss/p;' /config/nginx/site-confs/default.conf; then 
    cp /defaults/default.conf /config/nginx/site-confs/default.conf
fi

# disable updates
[[ -f /config/www/freshrss/data/config.php ]] && \
    sed -i "s|'disable_update' => false,|'disable_update' => true,|g" /config/www/freshrss/data/config.php

# set cronjob
[[ ! -f /config/crontabs/root ]] && \
    cp /defaults/root /config/crontabs/root
cp /config/crontabs/root /etc/crontabs/root

# permissions
chown -R abc:abc \
    /app/www/public \
    /config
